# .github/workflows/lambda-analysis.yaml
---
name: Lambda Analysis
on:
  workflow_dispatch:
    inputs:
      config_json_directory:
        description: Directory where the config JSON file is located.
        required: true
      config_json_name:
        description: Name of the config JSON file.
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        shell: bash
    environment:
      name: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-duration-seconds: 1800

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          audience: sts.amazonaws.com
          mask-aws-account-id: true
          role-duration-seconds: 900
          # role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-session-name: GitHubActions-LambdaAnalysis
          inline-session-policy: >-
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "AllowLambdaPowerTuning",
                  "Action": "",
                  "Resource": [
                    "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/cdk-hnb659fds-deploy-role-${{ secrets.AWS_ACCOUNT_ID }}-${{ vars.AWS_REGION }}",
                  ]
                }
              ]
            }
          output-credentials: false
          output-env-credentials: true
          unset-current-credentials: true
          disable-retry: false
          retry-max-attempts: 3
          use-existing-credentials: false
          allowed-account-ids: ${{ secrets.AWS_ACCOUNT_ID }}
          force-skip-oidc: false
          # action-timeout-s: 60

      - name: Run Lambda Power Tuning Script
        uses: ./.github/actions/aws-lambda-power-tuning
        env:
          CONFIG_JSON_DIRECTORY: ${{ github.workspace }}/${{ github.event.inputs.config_json_directory }}
        with:
          config_json_directory: ${{ env.CONFIG_JSON_DIRECTORY }}
          config_json_name: ${{ github.event.inputs.config_json_name }}
